# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
