# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggfarm', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='eggs_in_tray',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='prices',
            name='Px_per_Egg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prices',
            name='Px_per_Tray',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
