# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggfarm', '0004_auto_20180403_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='Px_per_Tray',
            field=models.PositiveIntegerField(),
        ),
    ]
