# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eggfarm', '0007_auto_20180403_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
