# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eggfarm', '0010_auto_20180403_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Prices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eggfarm.Prices'),
        ),
    ]
